### ISSUE TITLE
screw size and photoresitor

### ISSUE THREAD

**Issue by wawibu** [HarryVienna/WeatherStation-ESP32-Cases#1]
Hi Harald,
I found your webpage and like the display. Therefore I order one and also printed the case which fits nicely. 
Could you please share which screws you used for the case?
Would also be glad to know which photo resistor you used to ensure it would fit perfectly into the case.

Thanks in advance,
Torsten

**Comment by HarryVienna** [comment]
Hello Torsten,
I use M2x12 screws for the case. And as photo resistor I use this one: https://www.conrad.at/de/p/luna-optoelectronics-nsl-5112-fotowiderstand-ldr-to-18-tht-1-st-100-v-max-l-x-b-x-h-3-4-x-4-1-x-37-8-mm-1762890.html
Hope this helps :-)
Greetings from Vienna,
Harald
